name: "Deploy"

on: 
  push:
    branches:
      - "main"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connecting server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo "Connected to server"
            cd Projects/docker-redis
            echo "Stopping docker container"
            docker-compose stop
            echo "Pulling latest"
            git pull
            echo "Restarting"
            docker-compose up -d --build